### ISSUE TITLE
Handling FIXME, TODO in the code base.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#82]
* Have to fill list of TODO in the code.
- [ ] Have to implement `SQLAlchemy` to deal with MYSQL for Faster auto-resolve.
- [ ] To avoid alerts in holidays/leaves.
- [ ] Consider comment update date time.
- [ ] Fill the config hierarchy with default keys.
- [ ] Resolve doing multiple API calls.
- [ ] Handle exceed Github API rate limit.
